package com.citigroup.liquifi.autopilot.message.xstream;

public enum AdminCommand {
	GETMARKETDATA,
	SETMARKETDATA,
	DELETEORDER,
	DELETEBOOK,
	UNSOLCITEDCXLORDER,
	SETBOOKATTRIBUTES,
	GETBOOKATTRIBUTES,
	SETSYSTEMPROPERTIES,
	GETSYSTEMPROPERTIES,
	TRADERON,
	TRADEROFF;
}
