/*
 * MainPanel.java
 *
 * Created on September 17, 2008, 3:57 PM
 */

package com.citigroup.liquifi.autopilot.gui;

import com.citigroup.liquifi.autopilot.bootstrap.ApplicationContext;

/**
 *
 * @author  zy63334
 */
public class MainPanel extends javax.swing.JPanel {
	private static final long serialVersionUID = 1L;
	
	/** Creates new form MainPanel */
    public MainPanel() {
        initComponents();
        testcasePanel = ApplicationContext.getTestcasePanel();
        msgPanel = ApplicationContext.getMessagePanel();
        
        mainPanelSplitPane.setLeftComponent(testcasePanel);
        mainPanelSplitPane.setRightComponent(msgPanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanelSplitPane = new javax.swing.JSplitPane();

        setName("Form"); // NOI18N

        mainPanelSplitPane.setName("mainPanelSplitPane"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanelSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanelSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane mainPanelSplitPane;
    // End of variables declaration//GEN-END:variables
    
    private InputTestCasePanel testcasePanel;
    private MessagePanel msgPanel;

}
