/*
 * PreferenceDialog.java
 *
 * Created on September 22, 2008, 12:15 PM
 */

package com.citigroup.liquifi.autopilot.gui;

import java.util.Map;
import java.util.Map.Entry;

import javax.swing.JOptionPane;

import com.citigroup.liquifi.autopilot.bootstrap.ApplicationContext;
import com.citigroup.liquifi.autopilot.logger.AceLogger;
import com.citigroup.liquifi.util.Util;

/**
 *
 * @author  zy63334
 */
public class PreferenceDialog extends javax.swing.JDialog {
	private static final long serialVersionUID = 1L;
	private AceLogger logger = AceLogger.getLogger(this.getClass().getSimpleName());

	/** Creates new form PreferenceDialog */
	public PreferenceDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		init();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prefTabbedPane = new javax.swing.JTabbedPane();
        systemPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        systemTable = new javax.swing.JTable();
        tibcoPanel = new javax.swing.JPanel();
        initiatorAcceptorSplitPane = new javax.swing.JSplitPane();
        initiatorPanel = new javax.swing.JPanel();
        initiatorLabel = new javax.swing.JLabel();
        topicIDLabel1 = new javax.swing.JLabel();
        topicIDTextField1 = new javax.swing.JTextField();
        brokerLabel1 = new javax.swing.JLabel();
        brokerTextField1 = new javax.swing.JTextField();
        topicLabel1 = new javax.swing.JLabel();
        topicTextField1 = new javax.swing.JTextField();
        acceptorPanel = new javax.swing.JPanel();
        acceptorLabel = new javax.swing.JLabel();
        topicIDLabel2 = new javax.swing.JLabel();
        topicIDTextField2 = new javax.swing.JTextField();
        brokerLabel2 = new javax.swing.JLabel();
        brokerTextField2 = new javax.swing.JTextField();
        topicLabel2 = new javax.swing.JLabel();
        topicTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        topicIDLabel3 = new javax.swing.JLabel();
        topicIDTextField3 = new javax.swing.JTextField();
        brokerLabel3 = new javax.swing.JLabel();
        brokerTextField3 = new javax.swing.JTextField();
        topicLabel3 = new javax.swing.JLabel();
        topicTextField3 = new javax.swing.JTextField();
        securityPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        securityTable = new javax.swing.JTable();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);

        prefTabbedPane.setName("prefTabbedPane"); // NOI18N

        systemPanel.setName("systemPanel"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        systemTable.setModel(ApplicationContext.getSystemTableModel());
        systemTable.setName("systemTable"); // NOI18N
        jScrollPane2.setViewportView(systemTable);
        systemTable.getColumnModel().getColumn(0).setHeaderValue("Title 1");
        systemTable.getColumnModel().getColumn(1).setHeaderValue("Title 2");

        javax.swing.GroupLayout systemPanelLayout = new javax.swing.GroupLayout(systemPanel);
        systemPanel.setLayout(systemPanelLayout);
        systemPanelLayout.setHorizontalGroup(
            systemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, systemPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        systemPanelLayout.setVerticalGroup(
            systemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, systemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        prefTabbedPane.addTab("System", systemPanel);

        tibcoPanel.setName("tibcoPanel"); // NOI18N

        initiatorAcceptorSplitPane.setDividerLocation(125);
        initiatorAcceptorSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        initiatorAcceptorSplitPane.setName("initiatorAcceptorSplitPane"); // NOI18N

        initiatorPanel.setName("initiatorPanel"); // NOI18N

        initiatorLabel.setText("Initiators:");
        initiatorLabel.setName("initiatorLabel"); // NOI18N

        topicIDLabel1.setText("TopicID");
        topicIDLabel1.setName("topicIDLabel1"); // NOI18N

        topicIDTextField1.setName("topicIDTextField1"); // NOI18N

        brokerLabel1.setText("Broker");
        brokerLabel1.setName("brokerLabel1"); // NOI18N

        brokerTextField1.setName("brokerTextField1"); // NOI18N

        topicLabel1.setText("Topic ");
        topicLabel1.setName("topicLabel1"); // NOI18N

        topicTextField1.setName("topicTextField1"); // NOI18N

        javax.swing.GroupLayout initiatorPanelLayout = new javax.swing.GroupLayout(initiatorPanel);
        initiatorPanel.setLayout(initiatorPanelLayout);
        initiatorPanelLayout.setHorizontalGroup(
            initiatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initiatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(initiatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(initiatorPanelLayout.createSequentialGroup()
                        .addGroup(initiatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(initiatorPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(topicIDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(initiatorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(initiatorPanelLayout.createSequentialGroup()
                        .addGroup(initiatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(topicLabel1)
                            .addComponent(brokerLabel1))
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(initiatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topicTextField1)
                    .addComponent(brokerTextField1)
                    .addComponent(topicIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        initiatorPanelLayout.setVerticalGroup(
            initiatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initiatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(initiatorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(initiatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicIDLabel1)
                    .addComponent(topicIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(initiatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brokerLabel1)
                    .addComponent(brokerTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(initiatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicLabel1)
                    .addComponent(topicTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        initiatorAcceptorSplitPane.setLeftComponent(initiatorPanel);

        acceptorPanel.setName("acceptorPanel"); // NOI18N

        acceptorLabel.setText("Acceptors:");
        acceptorLabel.setName("acceptorLabel"); // NOI18N

        topicIDLabel2.setText("TopicID");
        topicIDLabel2.setName("topicIDLabel2"); // NOI18N

        topicIDTextField2.setName("topicIDTextField2"); // NOI18N

        brokerLabel2.setText("Broker");
        brokerLabel2.setName("brokerLabel2"); // NOI18N

        brokerTextField2.setName("brokerTextField2"); // NOI18N

        topicLabel2.setText("Topic ");
        topicLabel2.setName("topicLabel2"); // NOI18N

        topicTextField2.setName("topicTextField2"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        topicIDLabel3.setText("TopicID");
        topicIDLabel3.setName("topicIDLabel3"); // NOI18N

        topicIDTextField3.setName("topicIDTextField3"); // NOI18N

        brokerLabel3.setText("Broker");
        brokerLabel3.setName("brokerLabel3"); // NOI18N

        brokerTextField3.setName("brokerTextField3"); // NOI18N

        topicLabel3.setText("Topic ");
        topicLabel3.setName("topicLabel3"); // NOI18N

        topicTextField3.setName("topicTextField3"); // NOI18N

        javax.swing.GroupLayout acceptorPanelLayout = new javax.swing.GroupLayout(acceptorPanel);
        acceptorPanel.setLayout(acceptorPanelLayout);
        acceptorPanelLayout.setHorizontalGroup(
            acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acceptorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(acceptorPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(acceptorPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(acceptorPanelLayout.createSequentialGroup()
                                .addComponent(topicLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(acceptorPanelLayout.createSequentialGroup()
                                    .addComponent(topicIDLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18))
                                .addGroup(acceptorPanelLayout.createSequentialGroup()
                                    .addComponent(brokerLabel3)
                                    .addGap(23, 23, 23))))
                        .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topicTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(brokerTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(topicIDTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(acceptorPanelLayout.createSequentialGroup()
                        .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, acceptorPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(acceptorPanelLayout.createSequentialGroup()
                                        .addComponent(brokerLabel2)
                                        .addGap(19, 19, 19))
                                    .addComponent(topicIDLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addGroup(acceptorPanelLayout.createSequentialGroup()
                                        .addComponent(topicLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addComponent(acceptorLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(topicIDTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addComponent(brokerTextField2)
                            .addComponent(topicTextField2))
                        .addGap(20, 20, 20))))
        );
        acceptorPanelLayout.setVerticalGroup(
            acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acceptorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acceptorLabel)
                .addGap(11, 11, 11)
                .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicIDLabel2)
                    .addComponent(topicIDTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brokerLabel2)
                    .addComponent(brokerTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicLabel2)
                    .addComponent(topicTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicIDLabel3)
                    .addComponent(topicIDTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brokerLabel3)
                    .addComponent(brokerTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(acceptorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicLabel3)
                    .addComponent(topicTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        initiatorAcceptorSplitPane.setRightComponent(acceptorPanel);

        javax.swing.GroupLayout tibcoPanelLayout = new javax.swing.GroupLayout(tibcoPanel);
        tibcoPanel.setLayout(tibcoPanelLayout);
        tibcoPanelLayout.setHorizontalGroup(
            tibcoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initiatorAcceptorSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );
        tibcoPanelLayout.setVerticalGroup(
            tibcoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initiatorAcceptorSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        //prefTabbedPane.addTab("Tibco", tibcoPanel);

        securityPanel.setName("securityPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        securityTable.setModel(ApplicationContext.getSecurityTableModel());
        securityTable.setName("securityTable"); // NOI18N
        securityTable.setRequestFocusEnabled(false);
        securityTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(securityTable);
        securityTable.getColumnModel().getColumn(0).setResizable(false);
        securityTable.getColumnModel().getColumn(0).setHeaderValue("Security Class");
        securityTable.getColumnModel().getColumn(1).setResizable(false);
        securityTable.getColumnModel().getColumn(1).setHeaderValue("Symbol");

        javax.swing.GroupLayout securityPanelLayout = new javax.swing.GroupLayout(securityPanel);
        securityPanel.setLayout(securityPanelLayout);
        securityPanelLayout.setHorizontalGroup(
            securityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(securityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        securityPanelLayout.setVerticalGroup(
            securityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(securityPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );

        prefTabbedPane.addTab("Security", securityPanel);

        okButton.setText("Ok");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	ApplicationContext.getConfig().setDefaultSymbolMap(ApplicationContext.getSecurityTableModel().getDataMap());
            	Map<String, String> change = ApplicationContext.getSystemTableModel().getChange();
            	boolean problem = false;
            	for(Entry<String, String> item : change.entrySet()) {
            		try {
						ApplicationContext.getConfig().setContents(item.getKey(), item.getValue());
					} catch (Exception e) {
						problem = true;
						JOptionPane.showMessageDialog(null, Util.getStackTrace(e), "ERROR", JOptionPane.ERROR_MESSAGE);
						e.printStackTrace();
					}
            	}
            	
            	if(!problem) {
            		setVisible(false);
            	}
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(3, 3, 3)
                .addComponent(cancelButton)
                .addContainerGap())
            .addComponent(prefTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(prefTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
        
        // open on system properties tab
        prefTabbedPane.setSelectedIndex(0);
    }// </editor-fold>//GEN-END:initComponents

	public void init(){
		// bb load of bull!
		/*AutoPilotBrokerInfoFactory topicFactory = ApplicationContext.getBrokerFactory();
		AutoPilotBrokerInfo brokerInfo = topicFactory.getInitiatorBroker(AutoPilotConstants.MSG_TYPE_FIXMSG);
		topicIDTextField1.setText(brokerInfo.getTopicID());
		brokerTextField1.setText(brokerInfo.getBrokerURL());
		topicTextField1.setText(brokerInfo.getDestination());
		
		List<AutoPilotBrokerInfo> acceptorBrokerInfoList = topicFactory.getAcceptorBrokerList();
		AutoPilotBrokerInfo acceptor1 = acceptorBrokerInfoList.get(0);
		topicIDTextField2.setText(acceptor1.getTopicID());
		brokerTextField2.setText(acceptor1.getBrokerURL());
		topicTextField2.setText(acceptor1.getDestination());
		
		AutoPilotBrokerInfo acceptor2 = acceptorBrokerInfoList.get(1);
		topicIDTextField3.setText(acceptor2.getTopicID());
		brokerTextField3.setText(acceptor2.getBrokerURL());
		topicTextField3.setText(acceptor2.getDestination());
		*/
		ApplicationContext.getSecurityTableModel().setData(ApplicationContext.getConfig().getDefaultSymbolMap());
		ApplicationContext.getSystemTableModel().setData(ApplicationContext.getConfig().getContents());
	}


	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		this.setVisible(false);
	}//GEN-LAST:event_cancelButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				PreferenceDialog dialog = new PreferenceDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acceptorLabel;
    private javax.swing.JPanel acceptorPanel;
    private javax.swing.JLabel brokerLabel1;
    private javax.swing.JLabel brokerLabel2;
    private javax.swing.JLabel brokerLabel3;
    private javax.swing.JTextField brokerTextField1;
    private javax.swing.JTextField brokerTextField2;
    private javax.swing.JTextField brokerTextField3;
    private javax.swing.JButton cancelButton;
    private javax.swing.JSplitPane initiatorAcceptorSplitPane;
    private javax.swing.JLabel initiatorLabel;
    private javax.swing.JPanel initiatorPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton okButton;
    private javax.swing.JTabbedPane prefTabbedPane;
    private javax.swing.JPanel securityPanel;
    private javax.swing.JTable securityTable;
    private javax.swing.JPanel systemPanel;
    private javax.swing.JTable systemTable;
    private javax.swing.JPanel tibcoPanel;
    private javax.swing.JLabel topicIDLabel1;
    private javax.swing.JLabel topicIDLabel2;
    private javax.swing.JLabel topicIDLabel3;
    private javax.swing.JTextField topicIDTextField1;
    private javax.swing.JTextField topicIDTextField2;
    private javax.swing.JTextField topicIDTextField3;
    private javax.swing.JLabel topicLabel1;
    private javax.swing.JLabel topicLabel2;
    private javax.swing.JLabel topicLabel3;
    private javax.swing.JTextField topicTextField1;
    private javax.swing.JTextField topicTextField2;
    private javax.swing.JTextField topicTextField3;
    // End of variables declaration//GEN-END:variables

}
