/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SocketConnectionBox.java
 *
 * Created on Jul 21, 2009, 12:27:36 PM
 */

package com.citigroup.liquifi.autopilot.gui;

import java.util.HashMap;
import java.util.Map;

import com.citigroup.liquifi.autopilot.bootstrap.ApplicationContext;
import com.citigroup.liquifi.autopilot.messaging.SocketConnectionInfo;
import com.citigroup.liquifi.autopilot.socket.SocketWriter;

/**
 *
 * @author zy63334
 */
public class SocketMessageSenderBox extends javax.swing.JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form SocketConnectionBox */
    public SocketMessageSenderBox(java.awt.Frame parent) {
        super(parent);
        initComponents();
        for (SocketConnectionInfo socket : ApplicationContext.getSocketFactory().getSocketList()){
            socketStatus.put(socket.getSocketID(), false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        socketIDLabel = new javax.swing.JLabel();
        socketIDComboBox = new javax.swing.JComboBox();
        mesageLabel = new javax.swing.JLabel();
        messageScrollPane = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        cxlButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.jdesktop.application.SingleFrameApplication.class).getContext().getResourceMap(SocketMessageSenderBox.class);
        setTitle(resourceMap.getString("Socket Connection .title")); // NOI18N
        setName("Socket Connection "); // NOI18N
        setResizable(false);

        socketIDLabel.setText(resourceMap.getString("socketIDLabel.text")); // NOI18N
        socketIDLabel.setName("socketIDLabel"); // NOI18N

        if (ApplicationContext.getSocketFactory() != null) {
        	socketIDComboBox.setModel(new javax.swing.DefaultComboBoxModel(ApplicationContext.getSocketFactory().getSocketIDArray()));
        }
        
        socketIDComboBox.setName("socketIDComboBox"); // NOI18N

        mesageLabel.setText(resourceMap.getString("mesageLabel.text")); // NOI18N
        mesageLabel.setName("mesageLabel"); // NOI18N

        messageScrollPane.setName("messageScrollPane"); // NOI18N

        messageTextArea.setColumns(20);
        messageTextArea.setLineWrap(true);
        messageTextArea.setRows(5);
        messageTextArea.setName("messageTextArea"); // NOI18N
        messageScrollPane.setViewportView(messageTextArea);

        sendButton.setText(resourceMap.getString("sendButton.text")); // NOI18N
        sendButton.setName("sendButton"); // NOI18N
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        cxlButton.setText(resourceMap.getString("cxlButton.text")); // NOI18N
        cxlButton.setName("cxlButton"); // NOI18N
        cxlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxlButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(socketIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mesageLabel)
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendButton)
                        .addGap(18, 18, 18)
                        .addComponent(cxlButton)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(socketIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(120, 120, 120))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(messageScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(socketIDLabel)
                    .addComponent(socketIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesageLabel)
                    .addComponent(messageScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton)
                    .addComponent(cxlButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxlButtonActionPerformed
        messageTextArea.setText("");
        this.setVisible(false);
    }//GEN-LAST:event_cxlButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        String socketID = (String) socketIDComboBox.getSelectedItem();
        String text = messageTextArea.getText();
        SocketWriter.send(socketID, text);
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SocketConnectionBox dialog = new SocketConnectionBox(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cxlButton;
    private javax.swing.JLabel mesageLabel;
    private javax.swing.JScrollPane messageScrollPane;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JComboBox socketIDComboBox;
    private javax.swing.JLabel socketIDLabel;
    // End of variables declaration//GEN-END:variables
    
    private Map<String, Boolean> socketStatus = new HashMap<String, Boolean>();

}
