#! /bin/sh
#ident  "%W%"

export CLIENT_GATEWAY=C4C_UKDEV_CI_1
export CONNECTION_NAME_42=AUTOPILOT_CI-CGMI
export CUSOMTER_NAME_42=AUTOPILOT_CI
export SENDER_COMP_42=AUTOPILOT_CI
export TARGET_COMP_42=AUTOPILOT_CI

REGION=$1
APP=$2
ENVIRONMENT=$3
LABELS=$4

./start_emea.sh $1 $2 $3 $4 ""
